### ISSUE TITLE
Does not copy multiple license to output directory

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#441] opened 2020-08-28 08:26 UTC
Hello, I found a bug:
aboutCode-toolkit does not copy the licenses from the reference directroy if multiple licenses are given.

Create a .csv with content:
```
about_resource,name,version,license_key,license_file
3rdParty/test,test,1.5,"License1,License2,License3","LIC1.LICENSE,LIC2.LICENSE,LIC3.LICENSE"
```
Create some dummy license files in folder .\test-ReferenceTexts
run: `about gen --reference .\test-ReferenceTexts test.csv .\test-Output`
this will generate the file test-Output\3rdParty\test.ABOUT :
```
about_resource: test
name: test
version: '1.5'
licenses:
  - key: License1,License2,License3
    file: LIC1.LICENSE,LIC2.LICENSE,LIC3.LICENSE
```
but it will not copy LIC1, LIC2, LIC3 !

So a subsequent call to 
`about attrib --template test.html .\test-Output .\test-Output\test.html`
will fail, because it can't find the licenses where it expects them.

```
Running aboutcode-toolkit version 5.0.0
Generating attribution...
Command completed with 3 errors or warnings.
CRITICAL: 3rdParty/test.ABOUT: Field license_file: Path /test/test-Output/3rdParty/LIC1.LICENSE not found
CRITICAL: 3rdParty/test.ABOUT: Field license_file: Path /test/test-Output/3rdParty/LIC2.LICENSE not found
CRITICAL: 3rdParty/test.ABOUT: Field license_file: Path /test/test-Output/3rdParty/LIC3.LICENSE not found
Attribution generated in: \test\test-Output\test.html
```

This workflow works only if you had specified a single license and single license file.

**Comment by chinyeungli** [comment] 2020-08-28 09:59
@OctagonHex Thanks for reporting this.
I've used your sample but unfortunately cannot reproduce the issue that you're reporting.
input.csv
```
about_resource,name,version,license_key,license_file
3rdParty/test,test,1.5,"License1,License2,License3","LIC1.LICENSE,LIC2.LICENSE,LIC3.LICENSE"
```
comand:
```
about gen --reference C:\tmp\lics C:\tmp\input.csv C:\tmp\output
```
my output ABOUT file
```
# Generated with AboutCode Toolkit Version 5.0.0 

about_resource: test
name: test
version: '1.5'
licenses:
  - key: License1,License2,License3
    file: LIC1.LICENSE
  - file: LIC2.LICENSE
  - file: LIC3.LICENSE
```
and the LIC1.LICENSE , LIC2.LICENSE and L3.LICENSE are copied alright next to the generated ABOUT file.
That being said, the above generated ABOUT file is incorrect as the `file` field is messed up.

Back to the topic, if the component has multiple license key, we should separete the key by a line break instead of comma
i.e.
| about_resource  | name | version | license_key | license_file |
| ----------------- | ------ | -------- | ----------- | ------------ |
| 3rdParty/test  | test | 1.5 | License1<br>License2<br>License3 | LIC1.LICENSE<br>LIC2.LICENSE<br>LIC3.LICENSE |

The generated ABOUT file should look like:
```
# Generated with AboutCode Toolkit Version 5.0.0 

about_resource: test
name: test
version: '1.5'
licenses:
  - key: License1
    file: LIC1.LICENSE
  - key: License2
    file: LIC2.LICENSE
  - key: License3
    file: LIC3.LICENSE
```

If the license has 2 license_file that we want to reference, then the correct way to represent would be:
| about_resource  | name | version | license_key | license_file |
| ----------------- | ------ | -------- | ----------- | ------------ |
| 3rdParty/test  | test | 1.5 | License1<br>License2 | LIC1.LICENSE, LIC1.1.LICENSE<br>LIC2.LICENSE |

The generated ABOUT file should look like:
```
# Generated with AboutCode Toolkit Version 5.0.0 

about_resource: test
name: test
version: '1.5'
licenses:
  - key: License1
    file: LIC1.LICENSE, LIC1.1.LICENSE
  - key: License2
    file: LIC2.LICENSE
```

@OctagonHex Were there any error when you do the `gen` ?

**Comment by OctagonHex** [comment] 2020-08-28 11:34
OK thank you, your answer is very helpfull.
Now I have to figure out how to make a .csv with line-breaks from Excel.

Update: I updated my abouCode-toolkit to the latest version from GitHub, and now it works just as in your case.

**Comment by chinyeungli** [comment] 2020-08-28 12:50
@OctagonHex Great. Feel free to close this if you think this has been resolved.

**Comment by OctagonHex** [comment] 2020-08-31 05:22
If I close this issue now, it will be very hard for other people to find this information about multi-line fields.

Can you please add your examples to the documentation. I find them very good.

**Comment by chinyeungli** [comment] 2020-08-31 07:40
Update the Reference doc to have an example of multiple license_file for a license.
See https://github.com/nexB/aboutcode-toolkit/blob/develop/REFERENCE.rst#special-notes

**Closed as completed by chinyeungli** 2020-08-31 07:40 UTC
